apiVersion: v1
kind: Namespace
metadata:
  name: aceest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness
  namespace: aceest
  labels:
    app: aceest-fitness
    strategy: rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: aceest-fitness
      strategy: rolling
  template:
    metadata:
      labels:
        app: aceest-fitness
        strategy: rolling
        role: web
    spec:
      containers:
        - name: web
          image: docker.io/YOUR_DOCKER_ID/aceest-fitness:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness
  namespace: aceest
spec:
  selector:
    app: aceest-fitness
    role: web
  ports:
    - port: 80
      targetPort: 5000
